In [4]:
import warnings 
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import datetime
from datetime import date 

In [5]:
customers = pd.read_csv('customers.csv')
properties= pd.read_csv('properties.csv')

In [6]:
customers.head()


Unnamed: 0 CustomerID      entity     name   surname birth_date  sex  \
0         154      C0001     Company     Kamd        Co        NaN  NaN   
1         101      C0002  Individual     Jack  Anderson  2/13/1947    M   
2          93      C0003  Individual     Avah     Huang  4/23/1948    F   
3          77      C0004  Individual     Nora     Lynch  4/23/1948    F   
4          24      C0005  Individual  Rodolfo    Gibson  1/20/1937    M   

  country       state       purpose  deal_satisfaction mortgage   source  
0     USA  California    Investment                  5       No   Agency  
1     USA  California    Investment                  5      Yes  Website  
2     USA  California  Personal Use                  5       No  Website  
3     USA  California  Personal Use                  5       No  Website  
4     USA      Nevada  Personal Use                  2      Yes  Website

In [7]:
properties.head()

Unnamed: 0  homeid  building date_sale       type  property#     area  \
0         179    1005         1  3/1/2004     Office          5   410.71   
1         137    1002         1  3/1/2004     Office          2  1238.58   
2         132    1044         1  6/1/2004  Apartment         44   827.87   
3         133    1043         1  6/1/2004  Apartment         43  1160.36   
4         164    1033         1  8/1/2004  Apartment         33  1434.09   

          price  status CustomerID  
0  $117,564.07    Sold       C0001  
1  $410,932.67    Sold       C0002  
2  $229,464.71    Sold       C0003  
3  $377,313.56    Sold       C0004  
4  $412,856.56    Sold       C0005

Merge two datasets into one 

In [8]:
df= pd.merge(customers,properties,on='CustomerID',how='left')

In [9]:
df.columns

Index(['Unnamed: 0_x', 'CustomerID', 'entity', 'name', 'surname', 'birth_date',
       'sex', 'country', 'state', 'purpose', 'deal_satisfaction', 'mortgage',
       'source', 'Unnamed: 0_y', 'homeid', 'building', 'date_sale', 'type',
       'property#', 'area', 'price', 'status'],
      dtype='object')

Removing unwanted columns 

In [10]:
df= df.drop(['Unnamed: 0_x', 'entity', 'name', 'surname','state','Unnamed: 0_y','building','property#', 'status'],axis=1)

In [11]:
df.head(1)

CustomerID birth_date  sex country     purpose  deal_satisfaction mortgage  \
0      C0001        NaN  NaN     USA  Investment                  5       No   

   source  homeid date_sale    type    area         price  
0  Agency    1005  3/1/2004  Office  410.71  $117,564.07

Changing the column names for a better view

In [12]:
col_names = {
    'CustomerID':'CustomerID',
    'birth_date':'DoB',
    'sex':'Gender',
    'country':'Country',
    'purpose':'Purpose',
    'deal_satisfaction':'Satisfaction',
    'mortgage':'Mortgage',
    'source':'Source',
    'homeid':'PropertyID',
    'date_sale':'Date',
    'type':'Type',
    'area':'Area',
    'price':'Price',   
}
df=df.rename(columns = col_names)

In [13]:
df.columns

Index(['CustomerID', 'DoB', 'Gender', 'Country', 'Purpose', 'Satisfaction',
       'Mortgage', 'Source', 'PropertyID', 'Date', 'Type', 'Area', 'Price'],
      dtype='object')

In [14]:
col_order = ['CustomerID','DoB','Gender','Country','Purpose','Mortgage','Source','PropertyID','Type','Area','Price',
             'Satisfaction','Date']
df = df[col_order]

In [15]:
df.dtypes

CustomerID       object
DoB              object
Gender           object
Country          object
Purpose          object
Mortgage         object
Source           object
PropertyID        int64
Type             object
Area            float64
Price            object
Satisfaction      int64
Date             object
dtype: object

Changing the data types

In [16]:
df['PropertyID'].unique()

array([1005, 1002, 1044, 1043, 1033, 1038, 1018, 1021, 1036, 1045, 1035,
       1009, 1015, 1049, 1032, 1017, 1041, 1025, 1026, 1012, 1023, 1003,
       1006, 1027, 1011, 1029, 1030, 1007, 1008, 2023, 2030, 1016, 1040,
       1031, 1039, 1024, 2054, 2041, 2032, 3027, 1046, 2007, 2039, 2057,
       2037, 2005, 2050, 2026, 2015, 2033, 3015, 2029, 3007, 3030, 2020,
       2040, 2038, 2042, 4035, 4022, 3050, 2010, 2036, 2049, 2003, 2004,
       2006, 2044, 2022, 2011, 2047, 2014, 3001, 3043, 2025, 2018, 2009,
       2017, 2013, 3047, 2046, 2016, 2008, 2019, 2021, 2027, 2052, 3006,
       3044, 4025, 3031, 2048, 2028, 2043, 3049, 3034, 5033, 5035, 5039,
       2056, 2012, 3016, 3020, 3029, 5030, 3038, 3039, 3022, 3054, 3055,
       4031, 2035, 3008, 3040, 3025, 5016, 5019, 3059, 2034, 3021, 4051,
       3014, 2002, 3028, 3042, 3002, 3004, 3032, 3013, 3010, 3018, 2001,
       3046, 2051, 3019, 3011, 3026, 3005, 3033, 5013, 3012, 3048, 2024,
       4034, 3036, 4019, 5034, 4041, 4024, 4010, 40

In [17]:
df['PropertyID']=df['PropertyID'].astype('object')
print(df['PropertyID'].dtype)

object


In [18]:
df['Satisfaction'].unique()

array([5, 2, 3, 4, 1], dtype=int64)

In [19]:
df['Satisfaction']=df['Satisfaction'].astype('object')
print(df['Satisfaction'].dtype)

object


In [20]:
df['Price'].unique()

array(['$117,564.07 ', '$410,932.67 ', '$229,464.71 ', '$377,313.56 ',
       '$412,856.56 ', '$207,581.43 ', '$191,389.87 ', '$218,585.92 ',
       '$317,473.86 ', '$248,525.12 ', '$238,811.06 ', '$317,196.40 ',
       '$208,930.81 ', '$467,083.31 ', '$215,410.28 ', '$432,679.91 ',
       '$480,545.81 ', '$382,041.13 ', '$179,674.08 ', '$300,385.62 ',
       '$261,579.89 ', '$193,660.62 ', '$198,841.70 ', '$276,759.18 ',
       '$222,947.21 ', '$246,331.90 ', '$246,172.68 ', '$250,312.53 ',
       '$246,050.40 ', '$219,373.41 ', '$214,341.34 ', '$224,076.84 ',
       '$234,172.39 ', '$265,467.68 ', '$196,220.05 ', '$235,762.34 ',
       '$306,363.64 ', '$225,050.52 ', '$306,878.46 ', '$245,572.79 ',
       '$503,790.23 ', '$196,142.19 ', '$293,876.27 ', '$382,277.15 ',
       '$229,581.78 ', '$257,183.48 ', '$297,008.97 ', '$198,075.99 ',
       '$228,170.03 ', '$205,085.40 ', '$207,281.59 ', '$310,223.29 ',
       '$231,552.33 ', '$215,774.28 ', '$241,671.52 ', '$224,463.87 ',
      

In [21]:
df['Price']=pd.to_numeric(df['Price'].str.replace('[\$,]','',regex=True),errors ='coerce')

In [22]:
df['Price'].unique()

array([117564.07, 410932.67, 229464.71, 377313.56, 412856.56, 207581.43,
       191389.87, 218585.92, 317473.86, 248525.12, 238811.06, 317196.4 ,
       208930.81, 467083.31, 215410.28, 432679.91, 480545.81, 382041.13,
       179674.08, 300385.62, 261579.89, 193660.62, 198841.7 , 276759.18,
       222947.21, 246331.9 , 246172.68, 250312.53, 246050.4 , 219373.41,
       214341.34, 224076.84, 234172.39, 265467.68, 196220.05, 235762.34,
       306363.64, 225050.52, 306878.46, 245572.79, 503790.23, 196142.19,
       293876.27, 382277.15, 229581.78, 257183.48, 297008.97, 198075.99,
       228170.03, 205085.4 , 207281.59, 310223.29, 231552.33, 215774.28,
       241671.52, 224463.87, 529317.28, 220606.28, 217786.38, 263790.81,
       248274.31, 326885.34, 460001.26, 323915.81, 289727.99, 168834.04,
       396973.83, 250773.15, 344568.74, 225401.62, 214631.68, 336695.25,
       171262.65, 299159.14, 315733.15, 275394.25, 237060.15, 199054.2 ,
       236639.56, 188273.73, 253831.02, 212265.67, 

In [23]:
df['Price'].dtype

dtype('float64')

Checking the null Values 

In [28]:
def null(df):
    null_values = pd.DataFrame(df.isnull().sum())
    null_values[1] = null_values[0]/len(df)
    null_values.columns = ['count','%pct']
    filtered_null = null_values[null_values['%pct']>0]
    return filtered_null

In [29]:
null(df)

count      %pct
DoB        16  0.082474
Gender     16  0.082474

Dropping the null values

In [30]:
df=df.dropna(subset=['DoB','Gender'])

In [31]:
df['DoB']=pd.to_datetime(df['DoB'],format='%m/%d/%Y')
df['DoB']=pd.to_datetime(df['Date'],format='%m/%d/%Y')

In [32]:
df.sample(1)

CustomerID        DoB Gender Country     Purpose Mortgage   Source  \
20      C0021 2005-04-01      F  Russia  Investment       No  Website   

   PropertyID       Type    Area      Price Satisfaction      Date  
20       1023  Apartment  782.25  261579.89            3  4/1/2005

Calculating age instead of having date of birth

In [33]:
df['Age']= 2023-df['DoB'].dt.year
df=df.drop(['DoB'],axis = 1)
col_order = ['CustomerID','Age','Gender','Country','Purpose','Mortgage','Source','PropertyID','Type','Area','Price',
             'Satisfaction','Date']
df = df[col_order]

In [34]:
df.sample()

CustomerID  Age Gender Country       Purpose Mortgage   Source PropertyID  \
182      C0171   17      M     USA  Personal Use      Yes  Website       5051   

          Type    Area      Price Satisfaction      Date  
182  Apartment  790.54  249591.99            4  3/1/2006

In [36]:
df['Date'] = pd.to_datetime(df['Date'])

# Now you can perform datetime operations
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month_name()
df = df.drop(['Date'], axis=1)

In [37]:
df.duplicated().sum()

0

Checking if there is a customer having same property twice or not, regardless the other factors, because other factors might change 

In [38]:
df[df.duplicated(subset=['CustomerID','PropertyID'])]

Empty DataFrame
Columns: [CustomerID, Age, Gender, Country, Purpose, Mortgage, Source, PropertyID, Type, Area, Price, Satisfaction, Year, Month]
Index: []

Sanity check to identify and handle data values that fall outside the expected or valid range for a particular variable. Also, we can check the percentage of values that are negative 

In [39]:
num_var=['Age','Area','Price']
for i in range(len(num_var)):
    print('{},min:{},max:{}'.format(num_var[i],df[num_var[i]].min(),df[num_var[i]].max()))

Age,min:13,max:19
Area,min:579.75,max:1942.5
Price,min:153466.71,max:503790.23


In [40]:
def cat_checker(Var):
    unique_value=pd.Series(df[Var].unique()).sort_values().values
    return unique_value
    
    

In [41]:
df.sample(1)

CustomerID  Age Gender Country       Purpose Mortgage   Source PropertyID  \
96      C0086   15      F     USA  Personal Use       No  Website       5033   

         Type    Area      Price Satisfaction  Year Month  
96  Apartment  798.28  240539.35            1  2008   May

In [42]:
cat_checker('Gender')

array(['F', 'M'], dtype=object)

In [43]:
cat_checker('Purpose')

array(['Investment', 'Personal Use'], dtype=object)

In [44]:
cat_checker('Mortgage')

array(['No', 'Yes'], dtype=object)

In [45]:
cat_checker('Source')

array(['Agency', 'Client', 'Website'], dtype=object)

In [46]:
cat_checker('Type')

array(['Apartment', 'Office'], dtype=object)

In [47]:
cat_checker('Satisfaction')

array([1, 2, 3, 4, 5], dtype=object)

Age Distribution of Customers

In [48]:
def age_dist(country):
    country_df=df[df['Country']== country]
    age_range = pd.cut(
    country_df['Age'],
    bins=[0,30,50,70,100],
    labels= ['0-30','31-50','51-70','71-100'])
    return age_range.value_counts()

In [49]:
age_dist('Mexico')

0-30      1
31-50     0
51-70     0
71-100    0
Name: Age, dtype: int64

Average Price

In [50]:
def avg_price(country):
    country_df = df[df['Country'] == country]
    return country_df['Price'].mean()
unq_country=df['Country'].unique()
for country in unq_country:
    average_price= avg_price(country)
    print(f"Average price in {country}:{average_price}")

Average price in USA:271020.3746496815
Average price in Belgium:229075.47
Average price in Russia:278828.83499999996
Average price in USA :316315.58666666667
Average price in Denmark:257183.48
Average price in Canada:274069.38428571424
Average price in Mexico:338181.18
Average price in UK:220142.68
Average price in Germany:205098.21


Distribution of Sales across months and years

In [52]:
def sales_dist(country):
    country_df=df[df['Country'] == country]
    return country_df.groupby(['Year','Month']).size()

In [53]:
sales_dist('USA')

Year  Month    
2004  August        2
      June          2
      March         1
      November      2
      October       5
2005  August        2
      December      2
      February      1
      June          2
      March         4
      November      1
      October       1
2006  April         1
      August        5
      December      2
      February      1
      July          1
      June          4
      March         4
      May           1
      November      4
      October       5
      September     6
2007  April         7
      August        8
      December      8
      February      4
      January       4
      July          5
      June          7
      March        10
      May           6
      November     16
      October       7
      September     6
2008  December      3
      January       3
      May           3
2010  May           1
dtype: int64

Percentage of sales from each source 

In [60]:
def ads_effect(Country):
    country_df= df[df['Country']==Country]
    return country_df['Source'].value_counts(normalize=True)*100

In [61]:
ads_effect('UK')

Agency    100.0
Name: Source, dtype: float64

Correlation Analysis among age, price and area

In [62]:
def cor_age_price_area(country):
    country_df = df[df['Country']== country]
    return country_df[['Age','Price','Area']].corr()

In [63]:
cor_age_price_area('USA')

Age     Price      Area
Age    1.000000  0.091421  0.098156
Price  0.091421  1.000000  0.938110
Area   0.098156  0.938110  1.000000